# Generated by Django 4.2.7 on 2023-12-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_verifyemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyemail',
            name='phone',
        ),
    ]
