# Generated by Django 4.2.7 on 2023-12-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_verifyemail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyemail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
