# Generated by Django 4.2.7 on 2023-12-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_verifyemail_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyemail',
            name='verified',
        ),
    ]
