# Generated by Django 4.2.7 on 2023-12-04 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_nickname_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
