# Generated by Django 4.2.7 on 2024-01-23 21:07

import django.core.validators
from django.db import migrations, models
import product.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShangPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品')),
                ('exits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存')),
                ('uniqueID', models.CharField(default=uuid.UUID('e6d2e389-e907-4d29-954c-0c6840c5ce9f'), max_length=256, verbose_name='商品id')),
                ('price', models.FloatField(default=0.01, max_length=128, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='价格')),
                ('category', models.CharField(max_length=128, verbose_name='分类')),
                ('status', models.CharField(choices=[('0', '下架'), ('1', '在售'), ('2', '预售')], max_length=1, verbose_name='商品状态')),
                ('image', models.ImageField(upload_to=product.models.image_folder)),
                ('parameters', models.TextField(blank=True, verbose_name='商品参数')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
            ],
        ),
    ]
