# Generated by Django 4.2.7 on 2024-01-23 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangpin',
            name='category',
            field=models.CharField(max_length=128, verbose_name='商品分类'),
        ),
        migrations.AlterField(
            model_name='shangpin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='shangpin',
            name='uniqueID',
            field=models.CharField(default=uuid.UUID('17cdefbc-2063-416c-8df8-4544675e1a63'), max_length=256, verbose_name='商品id'),
        ),
    ]
