# Generated by Django 4.2.7 on 2024-01-23 22:40

from django.db import migrations, models
import product.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_shangpin_category_alter_shangpin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangpin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.image_folder, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='shangpin',
            name='uniqueID',
            field=models.CharField(default=uuid.UUID('3ba0737a-b2d3-4f0a-a929-dec964154cdf'), max_length=256, verbose_name='商品id'),
        ),
    ]
