# Generated by Django 4.2.7 on 2024-01-23 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_shangpin_description_alter_shangpin_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shangpin',
            name='id',
        ),
        migrations.AlterField(
            model_name='shangpin',
            name='uniqueID',
            field=models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False, verbose_name='商品id'),
        ),
    ]
