# Generated by Django 4.2.7 on 2024-01-23 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_shangpin_id_alter_shangpin_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangpin',
            name='uniqueID',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, verbose_name='商品id'),
        ),
    ]
