# Generated by Django 4.2.7 on 2024-01-27 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_alter_shangpin_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名称')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('re_name', models.CharField(max_length=128, verbose_name='重命名')),
                ('file_size', models.IntegerField(verbose_name='文件大小')),
                ('file', models.FileField(upload_to='file/%Y%m%d')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
