# Generated by Django 4.2.7 on 2023-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='9d1047b601574a47b7cc210e38dfb0d7', max_length=128, unique=True),
        ),
    ]
