# Generated by Django 4.2.7 on 2023-12-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
