# Generated by Django 4.2.7 on 2023-12-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
